"""Context Builder: renders items into PROJECT-CONTEXT.md. Output order is deterministic."""
from __future__ import annotations

from . import VERSION
from .model import DEV_PROVIDED, ITEM_SECTIONS, UNKNOWN, UNKNOWNS

HEADER_COMMENT = (
    f"<!-- Generated by project-context {VERSION}. Developer-provided entries and blocks between "
    "manual markers are preserved on update. -->"
)
MANUAL_START, MANUAL_END = "<!-- manual:start -->", "<!-- manual:end -->"


def _entry(item) -> list:
    lines = [f"- {item.statement} — {item.classification}"]
    if item.origin == "developer":
        lines.append(f"  Evidence: {DEV_PROVIDED}")
    elif item.evidence:
        lines.append("  Evidence: " + ", ".join(item.evidence))
    for n in item.notes:
        lines.append(f"  Note: {n}")
    return lines


def _sorted(items):
    return sorted(items, key=lambda i: (i.origin == "developer", i.statement))


def render(result, project: str, today: str, inspected: list, scope: str = "repository root") -> str:
    """result: merge.Result (items, freeform, extra_sections, manual_blocks)."""
    out = ["# Project Context", "", HEADER_COMMENT, "", "## Context Metadata", "",
           f"- Project: {project}", f"- Scope: {scope}", f"- Generated by: project-context {VERSION}", ""]
    by_section = {}
    for it in result.items:
        by_section.setdefault(UNKNOWNS if it.classification == UNKNOWN else it.section, []).append(it)

    def manual_after(section):
        for blk in result.manual_blocks:
            if blk[0] == section:
                out.extend(blk[1].strip("\n").splitlines() + [""])

    for sec in ITEM_SECTIONS:
        entries, free = by_section.get(sec, []), result.freeform.get(sec, [])
        if entries or free:
            out += [f"## {sec}", ""]
            for it in _sorted(entries):
                out += _entry(it)
            out += free
            out.append("")
        manual_after(sec)
    out += [f"## {UNKNOWNS}", ""]
    for it in _sorted(by_section.get(UNKNOWNS, [])):
        out += _entry(it)
    out += result.freeform.get(UNKNOWNS, [])
    out.append("")
    manual_after(UNKNOWNS)
    for title, body in result.extra_sections.items():
        out += [f"## {title}", ""] + body.strip("\n").splitlines() + [""]
    placed = set(ITEM_SECTIONS) | {UNKNOWNS}
    for blk in result.manual_blocks:  # blocks whose section no longer exists
        if blk[0] not in placed:
            out.extend(blk[1].strip("\n").splitlines() + [""])
    out += [
        "## Evidence", "",
        "- Confirmed: directly supported by the cited repository file, or stated by the developer.",
        "- Inferred: a qualified conclusion from the cited evidence. It is not a fact.",
        "- Unknown: not established by repository evidence. See Known Unknowns.",
        "- Configuration files were read for key names only. Values are never recorded.",
        "- Commands are recorded from files. None were run, and listing one is not evidence that it works.",
        "- Files that may hold secrets are listed by path only. Their contents were not read.",
        "",
        "## Context Freshness", "",
        f"- Last Reviewed: {today}",
        "- Context Owner: Unknown",
        "- Known Stale Sections: None known",
        "- Source Files Inspected:",
    ]
    out += [f"  - {p}" for p in inspected[:60]]
    if len(inspected) > 60:
        out.append(f"  - ... and {len(inspected) - 60} more")
    return "\n".join(out).rstrip("\n") + "\n"
