"""Command line: project-context generate | update [--repo PATH] [--dry-run] ..."""
from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
import tempfile
from pathlib import Path

from . import VERSION, builder, driftreport, existing, report
from .drift import analyze
from .config import load_config
from .detectors import run_all
from .merge import documentation_conflicts, merge
from .scanner import Repo
from .secrets import scrub
from .validators import validate


def emit(text: str, stream=None):
    """All terminal output goes through the scrubber."""
    print(scrub(text), file=stream or sys.stdout)


def _parser():
    p = argparse.ArgumentParser(prog="project-context", description="Generate or update PROJECT-CONTEXT.md from repository evidence, or check it for drift.")
    p.add_argument("command", choices=["generate", "update", "drift", "check"],
                   help="generate/update write the context; drift (alias: check) only reports whether it may be stale")
    p.add_argument("--repo", default=".", help="repository path (default: current directory)")
    p.add_argument("--output", help="context file path (default: <repo>/PROJECT-CONTEXT.md)")
    p.add_argument("--config", help="generator configuration file (default: <repo>/GENERATOR-CONFIG.md if present)")
    p.add_argument("--exclude", action="append", default=[], metavar="GLOB", help="additional path to exclude (repeatable)")
    p.add_argument("--dry-run", action="store_true", help="show what would be generated; write nothing")
    p.add_argument("--ci", action="store_true", help="drift only: concise output; exit 1 only when the context is materially stale or conflicting")
    p.add_argument("--date", help="review date, YYYY-MM-DD (default: today)")
    p.add_argument("--version", action="version", version=f"project-context {VERSION}")
    return p


def _material(old: str, new: str) -> bool:
    def norm(t):
        t = t.split("## Context Freshness")[0]
        t = re.sub(r"<!-- Generated by.*?-->", "", t)
        return "\n".join(l.rstrip() for l in t.strip().splitlines())
    return norm(old) != norm(new)


def _stale_note(parsed, cfg, today):
    if not cfg.stale_after_days:
        return None
    try:
        last = datetime.date.fromisoformat(parsed.last_reviewed)
    except ValueError:
        return "Existing context has no parseable review date and is treated as potentially stale."
    age = (today - last).days
    return f"Existing context was last reviewed {age} days ago (threshold: {cfg.stale_after_days})." if age > cfg.stale_after_days else None


def _write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".project-context-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _drift(args, root, cfg, out_path, old_text, today) -> int:
    """Read-only: inspect the repository, compare with the existing context, report. Writes nothing."""
    if old_text is None:
        emit(f"error: no existing context at {out_path}; nothing to compare. Run 'project-context generate' first", sys.stderr)
        return 2
    repo = Repo(root, cfg).scan()
    analysis = analyze(repo, run_all(repo), existing.parse(old_text), today, cfg.stale_after_days)
    shown = os.path.relpath(out_path, root) if out_path.is_absolute() and str(out_path).startswith(str(root)) else str(out_path)
    emit(driftreport.build_ci(analysis, shown) if args.ci else driftreport.build(analysis, shown))
    return 1 if args.ci and analysis.material else 0


def main(argv=None) -> int:
    args = _parser().parse_args(argv)
    drift_mode = args.command in ("drift", "check")
    if args.ci and not drift_mode:
        emit("error: --ci applies only to the drift command", sys.stderr)
        return 2
    root = Path(args.repo).expanduser().resolve()
    if not root.is_dir():
        emit(f"error: repository path is not a directory: {args.repo}", sys.stderr)
        return 2
    try:
        today = datetime.date.fromisoformat(args.date or os.environ.get("PROJECT_CONTEXT_DATE") or datetime.date.today().isoformat())
        cfg = load_config(root, args.config)
    except (ValueError, FileNotFoundError) as e:
        emit(f"error: {e}", sys.stderr)
        return 2
    cfg.excluded += args.exclude
    out_path = Path(args.output).expanduser() if args.output else root / cfg.output
    old_text = out_path.read_text(encoding="utf-8", errors="replace") if out_path.is_file() else None
    if args.command == "update" and old_text is None:
        emit(f"error: no existing context at {out_path}; run 'project-context generate' first", sys.stderr)
        return 2

    if drift_mode:
        return _drift(args, root, cfg, out_path, old_text, today)

    repo = Repo(root, cfg).scan()
    items = run_all(repo)
    for rel, desc in cfg.extra_sources:
        if repo.exists(rel):
            from .model import confirmed
            items.append(confirmed("Project Overview", f"Additional evidence source: {rel}" + (f" ({desc})" if desc else ""), rel))

    parsed = existing.parse(old_text) if old_text is not None else None
    result = merge(parsed, items, cfg.manual_sections)
    final_items = result.items
    result.conflicts.extend(documentation_conflicts(final_items))
    result.conflicts.extend(f"{f.path}: {f.kind} ({f.detail})" for f in repo.findings if f.kind.startswith("documentation"))
    inspected = sorted({e for i in final_items if i.origin == "generated" for e in i.evidence if e in repo.files})
    scope = "repository root" if not (cfg.included or cfg.max_depth) else "repository root, limited by configuration"
    text = builder.render(result, root.name, today.isoformat(), inspected, scope)

    errors = validate(text, repo, final_items)
    if errors:
        emit("Validation failed. Nothing was written.", sys.stderr)
        for e in errors[:20]:
            emit(f"  - {e}", sys.stderr)
        return 1

    mode = "update" if old_text is not None else "initial generation"
    stale = _stale_note(parsed, cfg, today) if parsed else None
    if args.dry_run:
        emit(report.build(repo, result, final_items, mode, args, "dry run: PROJECT-CONTEXT.md was not modified", old_text, text, stale))
        return 0

    if old_text is not None and not _material(old_text, text):
        if cfg.when_unchanged == "review-date":
            new_text = re.sub(r"(?m)^- Last Reviewed:.*$", f"- Last Reviewed: {today.isoformat()}", old_text)
            if new_text != old_text:
                _write(out_path, new_text)
                emit(report.build(repo, result, final_items, mode, args, "no material changes; review date updated", stale_note=stale))
                return 0
        emit("No material project context changes detected.")
        if stale:
            emit(stale)
        return 0

    _write(out_path, text)
    emit(report.build(repo, result, final_items, mode, args, f"wrote {out_path}", stale_note=stale))
    return 0
