"""Renders a drift Analysis as a human-readable report, or as a short CI summary. No scores."""
from __future__ import annotations

from .drift import CATEGORIES, INFO, MATERIAL, POTENTIAL

_RECOMMEND = {
    "DRIFT DETECTED": "PROJECT-CONTEXT.md should be reviewed and regenerated. Preview with `project-context update --dry-run`, "
                      "then run `project-context update` and review the result before committing.",
    "REVIEW RECOMMENDED": "Review the items above. Regenerate PROJECT-CONTEXT.md only if they change how the repository should be understood.",
    "NO DRIFT": "No action needed. The context is consistent with current repository evidence.",
}


def _short(text: str, n: int = 160) -> str:
    return text if len(text) <= n else text[: n - 1] + "…"


def _ev(f) -> str:
    return f"  Evidence: {', '.join(f.evidence)}" if f.evidence else ""


def build(a, context_path: str) -> str:
    out = ["# Project Context Drift Report", "", f"Status: {a.status}", ""]
    meta = [f"Context: {context_path}"]
    if a.last_reviewed:
        meta.append(f"last reviewed {a.last_reviewed}")
    if a.generator:
        meta.append(f"generated by project-context {a.generator}")
    out += [", ".join(meta), "", "This report is read-only. No file was changed.", ""]

    mat = a.by(MATERIAL)
    if mat:
        out += ["## Material Changes", ""]
        for cat in CATEGORIES:
            group = [f for f in mat if f.category == cat]
            if group:
                out += [f"### {cat}", ""]
                for f in group:
                    out.append(f"- {f.text}")
                    if f.evidence:
                        out.append(_ev(f))
                out.append("")
    pot = a.by(POTENTIAL)
    if pot:
        out += ["## Potentially Material", ""]
        for f in pot:
            out.append(f"- [{f.category}] {f.text}")
            if f.evidence:
                out.append(_ev(f))
        out.append("")

    conflicts = [f for f in a.findings if f.kind == "conflict"]
    if conflicts:
        out += ["## Conflicts", "",
                "Repository evidence is treated as current. The conflicting context statement is potentially stale. "
                "Neither is silently preferred: a developer decides.", ""]
        for f in conflicts:
            out += [f"- Context: \"{_short(f.context)}\"", f"  {f.text}"]
        out.append("")

    stale = [f for f in a.findings if f.context and f.kind in ("removed", "changed")]
    if stale:
        out += ["## Stale Context", "", "Potential stale context. These statements are documented but could not be confirmed. Nothing was deleted.", ""]
        for text in dict.fromkeys(_short(f.context) for f in stale):
            out.append(f"- \"{text}\"")
        out.append("")

    info = a.by(INFO)
    if info or a.notes:
        out += ["## Informational", ""]
        out += [f"- {f.text}" for f in info]
        out += [f"- {n}" for n in a.notes]
        out.append("")

    out += ["## Recommendation", "", _RECOMMEND[a.status], ""]
    return "\n".join(out)


def build_ci(a, context_path: str) -> str:
    mat, pot = a.by(MATERIAL), a.by(POTENTIAL)
    lines = [f"project-context drift: {a.status} ({len(mat)} material, {len(pot)} potentially material) [{context_path}]"]
    for f in mat:
        lines.append(f"  material [{f.category}] {f.text}" + (f" (evidence: {', '.join(f.evidence)})" if f.evidence else ""))
    for f in pot[:10]:
        lines.append(f"  review   [{f.category}] {f.text}")
    if len(pot) > 10:
        lines.append(f"  review   ... and {len(pot) - 10} more")
    if mat:
        lines.append("Run `project-context drift --repo .` for the full report, then `project-context update` and review the result.")
    return "\n".join(lines)
