"""Parses an existing PROJECT-CONTEXT.md (generated by this tool, or an earlier template-based one)."""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from .model import CLASSES, DEV_PROVIDED, ITEM_SECTIONS, LEGACY_SECTIONS, UNKNOWN, UNKNOWNS, Item

_MANUAL = re.compile(r"<!-- manual:start -->.*?<!-- manual:end -->", re.S)
_ENTRY = re.compile(r"^- (.+?) — (Confirmed|Inferred|Unknown)(?: — (.+))?\s*$")
_IGNORED = {"Project Context", "Context Metadata", "Evidence", "Context Freshness"}


@dataclass
class Parsed:
    items: list = field(default_factory=list)
    freeform: dict = field(default_factory=dict)
    extra_sections: dict = field(default_factory=dict)
    manual_blocks: list = field(default_factory=list)   # (section it followed, raw block)
    last_reviewed: str = ""
    raw: str = ""


def parse(text: str) -> Parsed:
    p = Parsed(raw=text)
    m = re.search(r"(?m)^- Last Reviewed:\s*(.+?)\s*$", text)
    p.last_reviewed = m.group(1) if m else ""

    # Manual blocks are lifted out first; they may contain their own headings.
    def lift(match):
        before = text[: match.start()]
        heads = re.findall(r"(?m)^## (.+?)\s*$", before)
        sec = _canon(heads[-1]) if heads else ""
        p.manual_blocks.append((sec, match.group(0)))
        return ""

    body = _MANUAL.sub(lift, text)
    sections, cur, buf = [], None, []
    for line in body.splitlines():
        h = re.match(r"^## (.+?)\s*$", line)
        if h:
            if cur is not None:
                sections.append((cur, buf))
            cur, buf = h.group(1).strip(), []
        elif cur is not None:
            buf.append(line)
    if cur is not None:
        sections.append((cur, buf))

    for title, lines in sections:
        name = _canon(title)
        if title in _IGNORED:
            continue
        if name in ITEM_SECTIONS or name == UNKNOWNS:
            _parse_items(p, name, lines)
        else:
            p.extra_sections[title] = "\n".join(lines)
    return p


def _canon(title: str) -> str:
    return LEGACY_SECTIONS.get(title, title)


def _parse_items(p: Parsed, section: str, lines: list):
    cur = None
    for line in lines:
        if not line.strip():
            continue
        m = _ENTRY.match(line)
        if m:
            stmt, cls, inline = m.group(1), m.group(2), (m.group(3) or "")
            dev = DEV_PROVIDED in inline.lower()
            cur = {"section": section, "statement": stmt, "cls": cls, "evidence": [] if dev else _ev(inline), "dev": dev}
            p.items.append(cur)
        elif cur is not None and re.match(r"^\s+Evidence:\s*", line):
            ev = re.sub(r"^\s+Evidence:\s*", "", line)
            if DEV_PROVIDED in ev.lower():
                cur["dev"] = True
            else:
                cur["evidence"] = _ev(ev)
        elif cur is not None and re.match(r"^\s+Note:", line):
            continue  # generator-owned, recomputed every run
        elif line.startswith("  ") and cur is not None:
            continue
        else:
            cur = None
            p.freeform.setdefault(section, []).append(line)
    p.items = [
        Item(i["section"], i["statement"], i["cls"], tuple(i["evidence"]), "developer" if i["dev"] else "generated")
        if isinstance(i, dict) else i
        for i in p.items
    ]


def _ev(text: str) -> list:
    return [e.strip() for e in re.split(r",\s*", text) if e.strip()]
