"""Context Validator: checks run before anything is written. Errors never include matched secret values."""
from __future__ import annotations

import re
from pathlib import PurePosixPath

from . import existing
from .model import CLASSES, CONFIRMED, INFERRED, UNKNOWN

REQUIRED_HEADINGS = ["Context Metadata", "Known Unknowns", "Evidence", "Context Freshness"]
_PATTERN_WORDS = re.compile(r"(?i)microservice|hexagonal|clean architecture|domain-driven|\bddd\b|\bcqrs\b|event-driven|monolith")
_ALLOWED_PATTERN_SOURCES = ("README states",)


def validate(text: str, repo, items: list) -> list:
    from .secrets import find_secrets

    errors = []
    lines = text.splitlines()
    if not lines or lines[0] != "# Project Context":
        errors.append("structure: document must start with '# Project Context'")
    outside = re.sub(r"<!-- manual:start -->.*?<!-- manual:end -->", "", text, flags=re.S)
    heads = re.findall(r"(?m)^## (.+?)\s*$", outside)
    for h in REQUIRED_HEADINGS:
        if h not in heads:
            errors.append(f"structure: missing required section '{h}'")
    dup = {h for h in heads if heads.count(h) > 1}
    if dup:
        errors.append(f"structure: duplicate sections: {', '.join(sorted(dup))}")
    if text.count("```") % 2:
        errors.append("markdown: unbalanced code fence")

    for name, lineno in find_secrets(text):
        errors.append(f"secret: secret-like content ({name}) at output line {lineno}; nothing was written")

    if not re.search(r"(?m)^- Last Reviewed: \d{4}-\d{2}-\d{2}\s*$", text):
        errors.append("freshness: Last Reviewed date is missing or not in YYYY-MM-DD form")
    if "- Generated by: project-context" not in text:
        errors.append("freshness: 'Generated by' metadata is missing")

    if not repo.root.is_dir():
        errors.append(f"repository: path is not a directory: {repo.root.name}")

    rendered = existing.parse(text)
    want = {(i.classification, i.statement) for i in items}
    got = {(i.classification, i.statement) for i in rendered.items}
    if want - got:
        errors.append(f"classification: {len(want - got)} entries lost their classification or format in rendering")

    for it in items:
        if it.classification not in CLASSES:
            errors.append(f"classification: invalid class on '{it.statement[:60]}'")
        if it.origin == "developer":
            continue
        if it.classification in (CONFIRMED, INFERRED) and not it.evidence:
            errors.append(f"evidence: no evidence reference for '{it.statement[:60]}'")
        for ev in it.evidence:
            if ev.startswith("/") or ".." in PurePosixPath(ev).parts:
                errors.append(f"evidence: unsafe path '{ev}'")
            elif ev not in repo.files and ev not in repo.dirs:
                errors.append(f"evidence: referenced path does not exist: {ev}")
        if it.classification != UNKNOWN and _PATTERN_WORDS.search(it.statement) and not it.statement.startswith(_ALLOWED_PATTERN_SOURCES):
            errors.append(f"claims: architecture pattern named without support: '{it.statement[:60]}'")
        if it.section == "Architecture" and it.classification == CONFIRMED and not it.statement.startswith("Decision records"):
            errors.append(f"claims: architecture statements must be Inferred or Unknown: '{it.statement[:60]}'")
    return errors
